# Project: 5.binary_tree
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = C:/Users/Administrator/Documents/main.o
LINKOBJ  = C:/Users/Administrator/Documents/main.o
LIBS     = -L"D:/Embarcadero_Dev-Cpp_6.3/TDM-GCC-64/lib" -L"D:/Embarcadero_Dev-Cpp_6.3/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Embarcadero_Dev-Cpp_6.3/TDM-GCC-64/include" -I"D:/Embarcadero_Dev-Cpp_6.3/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Embarcadero_Dev-Cpp_6.3/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/Embarcadero_Dev-Cpp_6.3/TDM-GCC-64/include" -I"D:/Embarcadero_Dev-Cpp_6.3/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Embarcadero_Dev-Cpp_6.3/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/Embarcadero_Dev-Cpp_6.3/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = 5.binary_tree.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = D:\Embarcadero_Dev-Cpp_6.3\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

C:/Users/Administrator/Documents/main.o: C:/Users/Administrator/Documents/main.cpp
	$(CPP) -c C:/Users/Administrator/Documents/main.cpp -o C:/Users/Administrator/Documents/main.o $(CXXFLAGS)
